// <auto-generated />

using System;
using JTracker.jtcontext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace JTracker.Migrations
{
    [DbContext(typeof(JTContext))]
    partial class JTContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932");

            modelBuilder.Entity("JesseTest.jtcontext.Models.Log", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DispositionDate");

                    b.Property<byte>("Dispositioned");

                    b.Property<DateTime>("Generated");

                    b.Property<byte>("LogLevel");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("SQL")
                        .HasColumnType("text");

                    b.Property<string>("SourcePage")
                        .HasColumnType("text");

                    b.HasKey("LogId");

                    b.ToTable("Log");
                });
#pragma warning restore 612, 618
        }
    }
}
